---
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_default.yml"
    path: "bixby_default.yml"
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_rails_enabled.yml"
    path: "bixby_rails_enabled.yml"
  - url: "https://raw.githubusercontent.com/samvera-labs/bixby/master/bixby_rspec_enabled.yml"
    path: "bixby_rspec_enabled.yml"
engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
    exclude_patterns:
      - spec/
  eslint:
    enabled: true
    config:
      extensions:
        - .es6
      ignore_warnings: true
  fixme:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-85
    config:
      file: .rubocop.cc.yml
ratings:
  paths:
  - "**.erb"
  - "**.rb"
  - "**.js"
  - "**.es6"
  - "**.rake"
  - "**.scss"
exclude_paths:
- config/
- db/
- node_modules/
- spec/fixtures/
- vendor/
- karma.conf.js
