version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dependabot-target'
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dependabot-target'